easy_admin:
    entities:
        Widget:
            class: App\Entity\Widget
            disabled_actions: ['delete', 'edit']
            list:
                role: ROLE_ADMIN
                actions:
                    - name: widget_edit
                      type: route
                      label: Edit
                    - name: admin_loggable_entity
                      type: route
                      label: Revisions

                fields:
                    - property: title
                    - property: createdBy
                    - property: createdAt
            form:
                role: ROLE_ADMIN
                fields:
                    - property: title

            show:
                role: ROLE_ADMIN
                fields:
                    - property: title
                    - property: statistics
                      template: statistics.html.twig

        User:
            class: App\Entity\User
            role_prefix: ROLE_ADMIN_USER
            disabled_actions: ['delete']
            list:
                fields:
                    - property: email
                    - property: enabled
                      type: boolean
                    - property: roles
                    - property: createdBy
                    - property: createdAt
                    - property: lastLogin
            form:
                fields:
                    - property: email
                    - property: enabled
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices:
                              ROLE_USER: ROLE_USER
                              ROLE_ADMIN: ROLE_ADMIN

            new:
                fields:
                    - property: email
                    - property: enabled
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices:
                              ROLE_USER: ROLE_USER
                              ROLE_ADMIN: ROLE_ADMIN
