easy_admin:
    entities:
        Widget:
            class: App\Entity\Widget
            role_prefix: ROLE_ADMIN_WIDGET
            list:
                actions: ['show']
                fields:
                    - property: title
                    - property: createdBy
                    - property: createdAt
            form:
                fields:
                    - property: title

            show:
                fields:
                    - property: title
                    - property: content
                    - property: content
                      template: content.html.twig

        User:
            class: App\Entity\User
            controller: App\Controller\Admin\UserController
            role_prefix: ROLE_ADMIN_USER
            list:
                fields:
                    - property: email
                    - property: enabled
                      type: boolean
                    - property: roles
                    - property: createdBy
                    - property: createdAt
                    - property: lastLogin
            form:
                fields:
                    - property: email
                    - property: enabled
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices:
                              ROLE_USER: ROLE_USER
                              ROLE_ADMIN: ROLE_ADMIN

            new:
                fields:
                    - property: email
                    - property: enabled
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices:
                              ROLE_USER: ROLE_USER
                              ROLE_ADMIN: ROLE_ADMIN
