fm_elfinder:
    assets_path: /components
    instances:
        default:
            locale: '%locale%'
            editor: ckeditor
            include_assets: true
            relative_path: true
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M # also file upload sizes restricted in php.ini
