# https://vfac.fr/blog/how-install-fosuserbundle-with-symfony-4
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: '%email_sender_address%'
        sender_name: '%email_sender_name%'
