#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check

was_bundle:
    resource: '@ItkDevWebAccessibilityStatementBundle/Resources/config/routing.php'
